### ISSUE TITLE
cannot launch after installation

### ISSUE THREAD

**Issue by noob2020** [bizarrechaos/pushbullet-client#1]
i'm is beginner so please hekp me::

Traceback (most recent call last):
  File "/usr/local/bin/pushbullet", line 9, in <module>
    load_entry_point('pushbullet-client==1.0', 'console_scripts', 'pushbullet')()
  File "build/bdist.linux-x86_64/egg/pushbullet/**main**.py", line 10, in main
  File "build/bdist.linux-x86_64/egg/docopt.py", line 558, in docopt
    DocoptExit.usage = printable_usage(doc)
  File "build/bdist.linux-x86_64/egg/docopt.py", line 468, in printable_usage
    raise DocoptLanguageError('"usage:" (case-insensitive) not found.')
docopt.DocoptLanguageError: "usage:" (case-insensitive) not found.

**Comment by bizarrechaos** [comment]
Hi @noob2020,

This is a work in progress. pushbullet-client is not complete yet.
Keep an eye on the repo for any changes.

Thanks,
bizarrechaos

**Comment by bizarrechaos** [comment]
@noob2020 just pushed the first version. Let me know if you are still having issues
